### ISSUE TITLE
Bug: "Snow! Real Magic!" Crash (+2 Extra Bugs)

### ISSUE THREAD

**Issue by AstromanGaming** [Talon396/EnhancedWeather#15]
**Describe the bug**
Hello, when I start the game with this mod and "Snow! Real Magic!", the game just crashes, but when I play without "Snow! Real Magic!", the game does not crash.

**To Reproduce**
1. Install EnhancedWeather & Snow! Real Magic!
2. Start Minecraft
3. Wait...
4. See in "latest" in logs

**Expected behavior**
Please fix this bug so that can play this amazing mod!

**Screenshots**
N/A

**System Information:**
 - OS: Windows 11 (22h2)
 - Minecraft Version: 1.19.2
 - Fabric/Quilt Loader Version: 0.14.10 (Fabric)
 - Fabric API Version: 0.67.1+1.19.2
 - EnhancedWeather Version: v1.0-Beta4
 - Loaded mods: ~380 Mods

**Additional context**

latest.log: https://gist.github.com/AstromanGaming/f108dd81acb8ca51a9e019dfbfc2f575

Also, I discovered two other bugs when I played without "Snow! Real Magic!". (I name them here to simplify life).

The first one, when I use the OP commands of the mod, 9/10 of the commands don't work, so I can't even spawn a tornado or anything else, but only rain.

The second, when it rains (I don't know about other weather phenomena), it rains everywhere even outside the rain clouds. It's possible that it's a conflict with the basic vanilla weather, but I'm not sure if by chance I activated the vanilla weather with a command or something.

Finally I like your mod concept, because it reminds me of the Forge mod homologue. ^^

**Comment by Talon396** [comment]
Hmm, very unusual. Let me check some of those bugs out.

**Comment by Talon396** [comment]
Okay, so the Snow! Real Magic! bug I can't fix because it's a mod conflict.
And the command thing isn't a bug. It's just that you haven't put all of the arguments in. You can type "/help enhancedweather summonOverworld" to see how to use the commands. And the rain outside of the rain cloud thing is normal. What's happening is that the rain transitions slowly outside of the rain cloud from 100% rain to 0% rain slowly. I added that to create a smooth transitional effect.

**Comment by AstromanGaming** [comment]
Ok, I will check this, thank you for your answer.
